apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytestapp-deployment
  labels:
    app: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testing
        image: testcoeregistry.azurecr.io/anilkrubandari130879/testing:1306
        ports:
        - containerPort: 80